### PR TITLE
Update Marquee.svelte to add closing tag

### PR DESCRIPTION
**Pull request by nmontavon**
I think this is literally it?

When editing my node_modules like this the error disappeared!

### CODE REVIEW

**Comment by nmontavon** [comment]
this closes #9 and doesn't impact backwards compatibility, please consider merging this. Thanks!

**Comment by nmontavon** [comment]
I will fork a completely updated version for svelte 5.

**Comment by WarningImHack3r** [comment]
@vyconm I just made a new one: https://github.com/WarningImHack3r/svelte-neomarquee

**Comment by nmontavon** [comment]
cool, thanks! this can be closed now, although updating it won't break anything in svelte 4.

**Pull request closed without merging**
